### ISSUE TITLE
'LoadWindow' object has no attribute 'load_algem_data'

### ISSUE THREAD

**Issue by jocavi89** [tgrbrooks/ADA#108]
Hello!

We tried uploading OD data to the ADA software using the template provided. However, when we want to load it, the following error message appears: 'LoadWindow' object has no attribute 'load_algem_data'. We made sure the date is in the correct format (year-month-day) and that we are using csv file. Wondering what the problem would be.

Best regards,

Jose

**Comment by tgrbrooks** [comment]
Hi Jose,

Thanks for bringing this to my attention, I'll look in to it this evening. 
Could you let me know what operating system you're using (Windows, Mac or Linux) and if you're using the prebuilt dmg/exe file or running the code directly with python?

**Comment by jocavi89** [comment]
> Hi Jose,
> 
> Thanks for bringing this to my attention, I'll look in to it this evening. Could you let me know what operating system you're using (Windows, Mac or Linux) and if you're using the prebuilt dmg/exe file or running the code directly with python?

We are using Windows and the template file provided by the ADA software (csv file). 

Thanks in advance

**Comment by tgrbrooks** [comment]
I've created a windows installer for the latest version of the code ([v1.2.0](https://github.com/tgrbrooks/ADA/releases/tag/v1.2.0)). 
Hopefully this will have fixed the problem, I've tested the new version on windows with a recently downloaded template and the [test file](https://github.com/tgrbrooks/ADA/blob/master/test/files/ADA/IP_T-Iso.csv) and both seem ok.
The template can be a bit fiddly though, so let me know if you're still having issues.

**Comment by jocavi89** [comment]
> I've created a windows installer for the latest version of the code ([v1.2.0](https://github.com/tgrbrooks/ADA/releases/tag/v1.2.0)). Hopefully this will have fixed the problem, I've tested the new version on windows with a recently downloaded template and the [test file](https://github.com/tgrbrooks/ADA/blob/master/test/files/ADA/IP_T-Iso.csv) and both seem ok. The template can be a bit fiddly though, so let me know if you're still having issues.

Hello! I installed the new version of ADA, and it works fine with the test file you mentioned. However, when I want to use the ADA template with our OD data, the following error message appears: list index out of range. Wondering what could be the problem.

Best,

Jose

**Comment by tgrbrooks** [comment]
If you're able to send me (tom.g.r.brooks@gmail.com) the first 10 lines of the file that should be enough for me to be able to diagnose the issue

**Comment by jocavi89** [comment]
> If you're able to send me ([tom.g.r.brooks@gmail.com](mailto:tom.g.r.brooks@gmail.com)) the first 10 lines of the file that should be enough for me to be able to diagnose the issue

Ok! Just sent you a mail
