### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lydiamapstone** [tgrbrooks/ADA#81]
When downloading the table it puts all the results into one cell instead of a cell per column for each growth curve. Nightmare.
Please fix ASAP!!

*Describe the bug**

**To Reproduce**

**Expected behavior**

**Extra information:**
 - OS: [e.g. Windows 10, macOS Mojave, etc]
 - Installation type: [e.g. via installer, via source code]

**Comment by tgrbrooks** [comment]
Fixed
